### ISSUE TITLE
Translations not applied [EN-NL]

### ISSUE THREAD

**Issue by AbelLykens** [storingbitcoin-info/website#16]
**What could be better**
not all texts are translated at fireprotection page

**On what page are you experiencing this problem**
http://storingbitcoin.info/#/fireprotection

**Additional context**
-

**Comment by Martinomagnifico** [comment]
You are nesting a UL inside a P. That's not allowed in HTML. The translate plugin uses innerHTML to change the well... inner HTML, and that will then break because it only allows valid HTML. Because the P is just a wrapper, remove it, and add the class and data-i18n to the UL. The robberysolutions has the same issue. Just don't put ULs inside P's.

Then in the translation JSON files, make sure that the `<ul>` and `</ul>` are gone too. That should fix it.

**Comment by AbelLykens** [comment]
Thank you for your insights @Martinomagnifico ! We'll look into it (later this week I think).

Great you are following the repo. Would have taken quite some time to figure this out I think.

**Comment by AbelLykens** [comment]
37bb6d1..e936024
fixed thank you @Martinomagnifico
